COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:database-1.chc8a4usconk.eu-north-1.rds.amazonaws.com@3306/lab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:database-1.chc8a4usconk.eu-north-1.rds.amazonaws.com@3306/lab4'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: Abonter7894!
